apiVersion: apps/v1
kind: Deployment
metadata:
  name: paie-service-app
  labels:
    app: paie-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paie-service-app
  template:
    metadata:
      labels:
        app: paie-service-app
    spec:
      containers:
        - name: paie-service-app
          image: moisegui/s5-paie-service:latest
          ports:
            - containerPort: 9001
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: USER_LOGIN
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: USER_PWD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE
            - name: BD_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BD_URL

---
apiVersion: v1
kind: Service
metadata:
  name: paie-service-svc
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - targetPort: 9001
      port: 80
  selector:
    app: paie-service-app
