apiVersion: apps/v1
kind: Deployment
metadata:
  name: virement-service-app
  labels:
    app: virement-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virement-service-app
  template:
    metadata:
      labels:
        app: virement-service-app
    spec:
      containers:
        - name: virement-service-app
          image: moisegui/s5-virement-service:latest
          ports:
            - containerPort: 9002
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: USER_LOGIN
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: USER_PWD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE
            - name: BD_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BD_URL

---
kind: Service
apiVersion: v1
metadata:
  name: virement-service-svc
spec:
  selector:
    app: virement-service-app
  ports:
    - port: 80
      targetPort: 9002
